name: CI/CD Pipeline

on:
  push:
    branches: [diaz]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # ‚úÖ AGREGAR TIMEOUT
    
    steps:
    - name: üßæ Checkout repository
      uses: actions/checkout@v4

    - name: üêç Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: üì¶ Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: üßπ Run lint (Ruff)
      run: |
        echo "üîç Analizando el c√≥digo con Ruff..."
        ruff check .

    - name: üîê Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: üèóÔ∏è Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./diaz
        push: true
        tags: ghcr.io/julianchavezdiaz/diaz:1.0.5
      
    - name: üßæ Mostrar variables b√°sicas
      run: |
        echo "Probando conexi√≥n SSH con:"
        echo "Host: ${{ secrets.VPS_HOST }}"
        echo "Usuario: ${{ secrets.VPS_USER }}"
        echo "Puerto: ${{ secrets.VPS_SSH_PORT }}"
    
    - name: üß™ Probar conexi√≥n SSH
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        password: ${{ secrets.VPS_PASSWORD }}
        port: ${{ secrets.VPS_SSH_PORT }}
        script: |
          echo "‚úÖ Conexi√≥n exitosa desde GitHub Actions"
          hostname
          whoami
          uptime

    - name: üß™ Probar conexi√≥n SCP
      uses: appleboy/scp-action@v1
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        password: ${{ secrets.VPS_PASSWORD }}
        port: ${{ secrets.VPS_SSH_PORT }}   
        source: "stack.yml"
        target: "/home/${{ secrets.VPS_USER }}/deploy"  

    - name: üß™ Despliegue de servicio
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        password: ${{ secrets.VPS_PASSWORD }}
        port: ${{ secrets.VPS_SSH_PORT }}   
        script: |
          echo "‚úÖ desplegando servicios"
          cd ~/deploy

          echo " descargando la imagen desde GIT"
          echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u julianchavezdiaz --password-stdin
          docker pull ghcr.io/julianchavezdiaz/diaz:1.0.5

          echo " deteniendo los servicios"
          docker stack rm diaz || true 

          echo "esperar 20 segundos..."
          sleep 20

          echo "desplegano el stack a los servicios"
          docker stack deploy --with-registry-auth -c stack.yml diaz

          docker ps